version: "3"
services:
  web:
    image: golang:1.18
    working_dir: /api
    volumes:
      - ./api:/api
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    links:
      - mysql
    networks:
      sail:
    command: go run main.go
  mysql:
    container_name: mysql
    image: "mysql/mysql-server:8.0"
    restart: always
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "sail-mysql:/var/lib/mysql"
      - "sail-mysql:/etc/mysql/conf.d"
      - "./db:/root/db"
    networks:
      sail:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s



networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
  sail-web:
    driver: local